### ISSUE TITLE
New category defining pipelines & contrasting with workflows

### ISSUE THREAD

**Issue by sadielbartholomew** [pditommaso/awesome-pipeline#112]
I think it would be very useful to have one or more (or nested) sections containing links to resources that:

* define & describe what pipelines are;
* clarifying how they differ to workflows, e.g. see #111, where I point out another 'awesome' list dedicated workflow engines: how does a pipeline tool differ from a workflow engine, other than by name (if at all except for the preferred term in a given field)?

**Comment by pditommaso** [comment]
Thanks for the suggestion, but it's out of the scope of this list.

**Comment by sadielbartholomew** [comment]
Fair enough, @pditommaso! Thanks for reading it, anyway.
