### ISSUE TITLE
add Just

### ISSUE THREAD

**Issue by leipzig** [pditommaso/awesome-pipeline#182]
this is a command or recipe runner that looks like Make but is built in Rust
https://github.com/casey/just

**Comment by pditommaso** [comment]
Please open a PR for it 🙏

**Comment by leipzig** [comment]
to be honest not sure what category. i guess it is still a build system

**Comment by pditommaso** [comment]
Then https://github.com/pditommaso/awesome-pipeline#build-automation-tools !

**Comment by leipzig** [comment]
https://github.com/pditommaso/awesome-pipeline/pull/183
