### ISSUE TITLE
Convert to table with more metadata

### ISSUE THREAD

**Issue by benpillet** [pditommaso/awesome-pipeline#68]
I'm looking through the list and happy to see so many available options.  As I start sorting to find one that will work for me, knowing what language each is implemented in and such would be helpful.  I can make a PR with my findings.  Would that be useful?  Besides language, is there anything else others would be interested in?

**Comment by pditommaso** [comment]
Thanks for your proposal, but I would prefer to keep it simple. A table structure would be more difficult to maintain.
