### ISSUE TITLE
Get DOI from Zenodo

### ISSUE THREAD

**Issue by jsmedmar** [pditommaso/awesome-pipeline#89]
This is a great resource, would be nice if it can be officially referenced. Perhaps get DOI from Zenodo?

https://zenodo.org/

**Comment by pditommaso** [comment]
That's a nice idea, but can do essentially the same just using the last Git commit ID. For example: 

https://github.com/pditommaso/awesome-pipeline/blob/7bfe2a72da435c0f128c5bde1160f964c1057b9d/README.md

That's immutable over time and does not required any manual operation.

**Comment by jsmedmar** [comment]
oh, does it mean that Zenodo is linked to a particular commit?

**Comment by remram44** [comment]
He is proposing using that permanent URL (to github.com) *instead of* a DOI.

**Comment by pditommaso** [comment]
Exactly.
